### ISSUE TITLE
Publish a release

### ISSUE THREAD

**Issue by mario-eth** [worldcoin/world-id-contracts#152]
Hello,

I'm one of the contributors to https://github.com/mario-eth/soldeer package manager.
This package manager is one of the default package managers for solidity, currently used by foundry.
We got a request to add this to our central repository but unfortunately, you are not present on npmjs nor have a release tag so we can use it.

Therefore, we would appreciate if you push this to https://soldeer.xyz/ yourself (you just need to create an account and then use foundry soldeer push or soldeer push (if you install soldeer as a standalone app) to push it to the repository under your own project). If this seems like a hurdle, we have a crawler that pushes various projects but for that to be possible we need the aforementioned things to be completed (either publish it to npmjs or create releases in github).

Thank you.

**Comment by Dzejkop** [comment]
Hey, we now have releases https://github.com/worldcoin/world-id-contracts/releases

Is this enough or do we still need to publish to npm?

**Comment by mario-eth** [comment]
Awesome, thank you! it's published.
