### ISSUE TITLE
Support different batch sizes

### ISSUE THREAD

**Issue by kustosz** [worldcoin/world-id-contracts#16]
The contract should hold on to a (possibly dynamically settable) set of verifiers for batch inserts of different sizes. This will allow the sequencer to adapt to different load levels without wasting compute on almost-empty batches.

The basic outline of how this should happen is as follows:

- [ ] Add a set of dispatch tables. These should take the batch size and convert it to the correct verifier to use for each endpoint (identity registration, removal, and update).
- [ ] Use this dispatch table in the identity registration, removal, and update endpoints.
- [ ] Update the getters and setters to allow for getting and setting verifiers on a per-size basis, rather than just globally.
- [ ] Update `initialize` to take an array of `(uint256 size, ITreeVerifier verifier)` pairs for each dispatch table.
- [ ] Add tests to ensure that the correct verifier gets dispatched to. This can be done by adding a basic event and having the test verifiers emit different values to the log depending on the batch size.
- [ ] Update the deploy script so that it can be used with the new architecture.
- [ ] Update Signup Sequencer so the contract interface it stores is up to date with the changes.
- [ ] Account for the potentially-variable batch sizes in the DRP.

**Comment by gswirski** [comment]
Not sure if we need to do this. This work depends on benchmarking of prod traffic once we deploy everything.

Three areas of work:
* contract: set a sequence of verifiers, dispatch calls to various verifiers,
* prover: deploy multiple instances
* sequencer: dispatch to various provers based on _conditions_

**Comment by iamrecursion** [comment]
Split this issue up into multiple. This issue now accounts purely for the Identity Manager portion of this work. The rest is below:

- Signup Sequencer: https://github.com/worldcoin/signup-sequencer/issues/415
- Prover Service: https://github.com/worldcoin/semaphore-mtb/issues/17
