### ISSUE TITLE
Provide stub API for member removals / updates

### ISSUE THREAD

**Issue by kustosz** [worldcoin/world-id-contracts#17]
Figure out the signatures and provide stub implementations for member removal / update operations. They should delegate to some (as yet uninitialized but settable in the future) verifier contracts, that will be able to actually verify modification correctness. This will save us some upgrade pain in the future.

**Comment by iamrecursion** [comment]
I disagree that the delegate contracts should be uninitialised. They should exist and should just revert with `Unsupported` instead.

**Comment by iamrecursion** [comment]
This task should also include adding setters for the existing delegate contracts to allow upgrades or alterations without the need for a full upgrade of the identity manager.
